In [1]:
import pandas as pd

file_path = r'C:\Users\Salma\Downloads\Arabic_Preprocissing_data-main\Arabic_Preprocissing_data-main\FinishedDataset.csv'
data =pd.read_csv(file_path)
data

Unnamed: 0  Unnamed: 0.1  \
0               0             0   
1               1             0   
2               2             0   
3               3             0   
4               4             0   
...           ...           ...   
29866       29995          5999   
29867       29996          5999   
29868       29997          5999   
29869       29998          5999   
29870       29999          5999   

                                   Arabic_Tweets_Cleaned label  
0      اضافه قيام معلمو جيزه ذهاب جريد سابع نشر خبر ا...   MSA  
1      بركه زار خدم مدنيه زار تربيه تعليم خريج خريج خ...   MSA  
2                                                    شكر   MSA  
3      مبرووك لكن خلي صاحب مركز رابع عشر لعب صاحب مرك...   MSA  
4      راح وصل ماء ابدا لو حطو ماسور خمسون انش لانهاش...   MSA  
...                                                  ...   ...  
29866                             صاير ثقيل دم معكوس راح   MSA  
29867  انو مجتمع اردني اكثر مجتمع عربيه تعليم وعي ثقا...   MSA  
29868              صانع بطاله هم عامل وافده متي تنفس بلد   MSA  
29869  اما رقم ابراهيم مصري تحدث قاعد امريكي جزاءر مك...   MSA  
29870                              امطار ماشاء الله اكثر   MSA  

[29871 rows x 4 columns]

In [2]:
text = data['Arabic_Tweets_Cleaned'].values.tolist()
target = data['label'].values.tolist()

In [3]:
print(text[:10])

['اضافه قيام معلمو جيزه ذهاب جريد سابع نشر خبر اتي عام', 'بركه زار خدم مدنيه زار تربيه تعليم خريج خريج خدم اجتماعيه لا وظيف اوموظفين مسمى وظيفي اخري واحد من', 'شكر', 'مبرووك لكن خلي صاحب مركز رابع عشر لعب صاحب مركز سادس عشر خلا نشوف', 'راح وصل ماء ابدا لو حطو ماسور خمسون انش لانهاشبار ماسورة قبل موظف فتح ناس أغلق ناس اسبوع ماضي خميس لم نزل قطر ماء واحد ساعي ماء جاء مراقب ماء عادة مثل حم عروس لا أقبل كان شو اج نهاي دوام مسلسل سلط ماء حي مسجد ابو بكر صديق مابعرف شو راح مسلسل لدى سلط رمضان', 'بعد الله حرام تجي تلقي واقف اشاره عرض متعدي ناس خط مشاه مصيبه واقف قدام رجل مرور لكن لا كان', 'شرط خدم', 'توفيق زعيم مشكوور شبيه ريح ومشكوور خالد بلط جدار شا الله نهاءي سعودي', 'عشان مقيم أيقظ', 'موسم غض نظر فوز خساره هناك انتصار مصاحب اخطاء مميت ساعد عدم تحقيق بطولة نور مثل كم مشكلة اشكالي تسبب موسم خسر اتحاد كثير بطولة محليه خارجيه استفاد خبرة ادار انديه اوربيه ياباني']


In [4]:
from sklearn.feature_extraction.text import CountVectorizer


count_vect = CountVectorizer()
counts = count_vect.fit_transform(text)

In [5]:
from sklearn.feature_extraction.text import TfidfTransformer

transformer = TfidfTransformer().fit(counts)

counts = transformer.transform(counts)

In [6]:
from sklearn.model_selection import train_test_split
#X_train, X_test, y_train, y_test = train_test_split(data['Arabic_Tweets_Cleaned'], data['label'],test_size=0.2, shuffle = True, random_state=42)
X_train, X_test, y_train, y_test = train_test_split(counts,target,test_size=0.2, shuffle = True,  random_state=69)


In [4]:
#from sklearn.feature_extraction.text import CountVectorizer
#count_vect = CountVectorizer()
#X_train_counts = count_vect.fit_transform(X_train)
#X_train_counts.shape


(4, 3)

In [5]:
#count_vect.vocabulary_.get(u'اكثر')


In [8]:
#from sklearn.feature_extraction.text import TfidfTransformer
#tf_transformer = TfidfTransformer(use_idf=False).fit(X_train_counts)
#X_train_tf = tf_transformer.transform(X_train_counts)
#X_train_tf.shape

In [7]:
#tfidf_transformer = TfidfTransformer()
#X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)
#X_train_tfidf.shape

In [9]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB().fit(X_train, y_train)

In [10]:
import numpy as np
from sklearn.metrics import accuracy_score
predicted = clf.predict(X_test)

precision = accuracy_score(predicted, y_test) * 100
print("Accuracy with Multinomial Naive Bayes: {0:.6f}".format(precision))

Accuracy with Multinomial Naive Bayes: 58.376569


In [11]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, predicted))

[[   0    0    0  705]
 [   0    0    0 1159]
 [   0    0    0  620]
 [   0    3    0 3488]]


In [12]:
from sklearn import svm
svm_clf = svm.SVC()
svm_clf = svm_clf.fit(X_train, y_train)

C:\Users\Salma\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [13]:
test_predictions = svm_clf.predict(X_test)

In [13]:
precision = accuracy_score(test_predictions, y_test) * 100
print("Accuracy with SVM: {0:.6f}".format(precision))

Accuracy with SVM: 58.402142
