In [1]:
import pandas as pd

file_path = r'C:\Users\Salma\Downloads\Arabic_Preprocissing_data-main\Arabic_Preprocissing_data-main\All_Data_Cleaned.csv'
data =pd.read_csv(file_path)
data

Arabic_Tweets_Cleaned labels_new
0      اضافه قيام معلمو جيزه ذهاب جريد سابع نشر خبر ا...        MSA
1      بعد الله حرام تجي تلقي واقف اشاره عرض متعدي نا...        MSA
2                                 لمس يد مرة واضح جد حكم   DIAL_LEV
3                                خصوص هاتريك عمر راح صار   DIAL_LEV
4                         الله أجبر كسر رجع أدهم قبل بكر   DIAL_GLF
...                                                  ...        ...
85278                                      بورسعيد حكاية   DIAL_LEV
85279                 نعم لبس زي رسمي سعودي نظر علي اعين        MSA
85280    اتوقع الله اعلم قصد بقي شعب مسافر شل عد لا كلام   DIAL_GLF
85281                                              يتبدا   DIAL_EGY
85282  عامر ذيب شد حيلة عامر هناك تراجع مستواك حركة ا...   DIAL_LEV

[85283 rows x 2 columns]

In [2]:
text = data['Arabic_Tweets_Cleaned'].values.tolist()
target = data['labels_new'].values.tolist()

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(text,target,test_size=0.2, shuffle = True,  random_state=42)


In [4]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

count_vect = CountVectorizer() 
X_train_counts = count_vect.fit_transform(X_train) 
tfidf_transformer = TfidfTransformer()
X_tfidf_train = tfidf_transformer.fit_transform(X_train_counts)
X_test_counts = count_vect.transform(X_test) 
X_tfidf_test = tfidf_transformer.transform(X_test_counts)

In [14]:
from imblearn.under_sampling import NearMiss
undersample = NearMiss(version=1, n_neighbors=3)
# transform the dataset
X, Y = undersample.fit_resample(X_tfidf_train, y_train)

In [8]:
X_tfidf_train.shape

(23896, 28394)

In [9]:
X_tfidf_test.shape

(5975, 28394)

In [ ]:
# Multinomial Naive Bayes classifier

In [5]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB().fit(X_tfidf_train, y_train)

In [6]:
import numpy as np
from sklearn.metrics import accuracy_score
predicted = clf.predict(X_tfidf_test)

precision = accuracy_score(predicted, y_test) * 100
print("Accuracy with Multinomial Naive Bayes: {0:.6f}".format(precision))

Accuracy with Multinomial Naive Bayes: 68.546638


In [7]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, predicted))

[[ 594   57   10 1368]
 [   9  930   12 2359]
 [  17   92  325 1354]
 [   5   78    4 9843]]


In [8]:
from sklearn.metrics import classification_report

print(classification_report(y_test,predicted))


              precision    recall  f1-score   support

    DIAL_EGY       0.95      0.29      0.45      2029
    DIAL_GLF       0.80      0.28      0.42      3310
    DIAL_LEV       0.93      0.18      0.30      1788
         MSA       0.66      0.99      0.79      9930

    accuracy                           0.69     17057
   macro avg       0.83      0.44      0.49     17057
weighted avg       0.75      0.69      0.63     17057



In [18]:
import pickle 
  
saved_MNB_model = pickle.dumps(clf) 
  
# Load the pickled model 
MNB_from_pickle = pickle.loads(saved_MNB_model) 
  


In [ ]:
# SVM Classifier

In [9]:
from sklearn import svm
svm_clf = svm.SVC()
svm_clf = svm_clf.fit(X_tfidf_train, y_train)

In [11]:
test_predictions = svm_clf.predict(X_tfidf_test)

In [12]:
import numpy as np
from sklearn.metrics import accuracy_score
precision = accuracy_score(test_predictions, y_test) * 100
print("Accuracy with SVM: {0:.6f}".format(precision))

Accuracy with SVM: 78.114557


In [13]:
from sklearn.metrics import classification_report
print(classification_report(y_test,test_predictions))

              precision    recall  f1-score   support

    DIAL_EGY       0.87      0.58      0.69      2029
    DIAL_GLF       0.76      0.53      0.62      3310
    DIAL_LEV       0.87      0.47      0.61      1788
         MSA       0.77      0.96      0.86      9930

    accuracy                           0.78     17057
   macro avg       0.82      0.63      0.70     17057
weighted avg       0.79      0.78      0.76     17057



In [17]:
saved_SVM_model = pickle.dumps(svm_clf) 
  
# Load the pickled model 
SVM_from_pickle = pickle.loads(saved_SVM_model) 

In [24]:
sentence = ['كيف حالك']
X_testing_counts = count_vect.transform(sentence) 
X_tfidf_testing = tfidf_transformer.transform(X_testing_counts)

SVM_from_pickle.predict(X_tfidf_testing)

array(['MSA'], dtype='<U8')